### ISSUE TITLE
DRV8834

### ISSUE THREAD

**Issue by AlexLazarovich** [pololu/drv8835-motor-driver-rpi#5]
Is this also compatible for the DRV8834?

**Comment by kevin-pololu** [comment]
This library is for the [Pololu DRV8835 Dual Motor Driver Kit for Raspberry Pi](http://www.pololu.com/product/2753), which is designed to plug directly into a Raspberry Pi. You might be able to adapt it to control two brushed DC motors with a DRV8834, but it's not going to do much for you beyond what you could do yourself using the WiringPi library. You can look at pololu_drv8835_rpi.py to see how it works.
